# QASPER检索评估系统配置文件
# Configuration file for QASPER Retrieval Evaluation System

# 数据集配置 / Dataset Configuration
dataset:
  name: "allenai/qasper"
  cache_dir: "./cache"
  download_timeout: 3600
  max_samples: null  # null表示使用全部数据 / null means use all data
  splits: ["train", "validation", "test"]

# 模型配置 / Model Configuration
models:
  embedding_model: "moka-ai/m3e-base"
  embedding_dim: 768
  max_seq_length: 512
  batch_size: 32
  device: "cuda"  # cuda, cpu, auto

# BM25配置 / BM25 Configuration
bm25:
  k1: 1.2
  b: 0.75
  epsilon: 0.25
  tokenizer: "jieba"  # jieba, nltk, spacy

# FAISS配置 / FAISS Configuration
faiss:
  index_type: "IndexFlatIP"  # IndexFlatL2, IndexFlatIP, IndexIVFFlat
  nlist: 100  # for IVF index
  nprobe: 10  # for IVF search
  save_index: true
  index_path: "./cache/faiss_index"

# 混合检索配置 / Hybrid Retrieval Configuration
hybrid:
  bm25_weight: 0.5
  embedding_weight: 0.5
  normalization: "min_max"  # min_max, z_score, softmax

# 评估配置 / Evaluation Configuration
evaluation:
  metrics: ["rouge", "bleu", "meteor"]
  rouge_types: ["rouge1", "rouge2", "rougeL"]
  bleu_types: ["bleu1", "bleu4"]
  top_k: [1, 3, 5, 10]
  save_results: true
  results_dir: "./results"

# 检索配置 / Retrieval Configuration
retrieval:
  top_k: 10
  min_score_threshold: 0.0
  max_passage_length: 1000
  overlap_threshold: 0.8

# 日志配置 / Logging Configuration
logging:
  level: "INFO"
  format: "{time:YYYY-MM-DD HH:mm:ss} | {level} | {name}:{function}:{line} | {message}"
  file_path: "./logs/qasper_retrieval.log"
  rotation: "100 MB"
  retention: "30 days"

# 性能配置 / Performance Configuration
performance:
  num_workers: 4
  prefetch_factor: 2
  pin_memory: true
  use_multiprocessing: true
  max_memory_usage: "8GB"

# 实验配置 / Experiment Configuration
experiment:
  name: "qasper_retrieval_experiment"
  description: "Comparison of BM25, Embedding, and Hybrid retrieval methods"
  random_seed: 42
  save_intermediate_results: true